# ========================
# SMTP SERVER
# ========================
smtp_server: "smtp.gmail.com"
smtp_gmail_user_name: "support@voroninstudio.eu"
smtp_gmail_domain: "voroninstudio.eu"
smtp_gmail_password: "VS-support#201604"
smtp_default_from: "support@voroninstudio.eu"

# ========================
# HOST
# ========================
development.host: "localhost:3000"

# ========================
# TINYPNG
# ========================
tinypng_key: "JFFZudld0q3AJkZogWZmy5d0wl-1My53"

# ========================
# DATABASE
# ========================
default_adapter: "*sqlite"
database: "db/development.sqlite3"
# ========================
# DEVISE
# ========================
devise_secret_key: 'f08bf5395e4aee5c3ebfd7c41b4462503d6dc54ca4c37274c56536bc6afb812c68fd4c20644b5083f937b1f8636af1088988945c9bc7d414c91a4691afab48ab'

# ========================
# SECRET_KEY
# ========================
SECRET_KEY_BASE: 'ff7c8e95b19783a523a56c87a6626fcb5b0f1f6f60f6877d7608ef76ef01efd13e8271e31d79fc93747b433bb5dd8e9b8e20520ba1767a3befb6dfa23d021b55'

# ========================
# GOOGLE MAPS
# ========================
GOOGLE_MAPS_API_KEY: "AIzaSyAvkI36T-T6xJe8Qif7QkbQ1xvTl8Ha_9o"
#file_editor_base_dir: "/media/data/projects/ekran/config"


# ========================
# MAILCHIMP
# ========================
MAILCHIMP_API_KEY: "70e7e349e5073831ae7f31fdd470701e-us11"
MAILCHIMP_LIST_ID: "3cb6a1b126"
